name: 2048 Game

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install tkinter

      - name: Run 2048 game
        run: python 2048_game.py
